const productos = [
    {
        id: 1,
        nombre: "Alocasia negra",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//alocasia%20x%20amazonica%20-%20c12.jpg",
        descripcion: "Esta alocasia posee un follaje remarcable, verde oscuro con unos reflejos metálicos de un verde más claro.",
        precio: 16.50,
        stock: 10,
    },
    {
        id: 2,
        nombre: "Aloe vera",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//aloe%20barbadensis.jpg",
        descripcion: "El aloe vera tiene muchas virtudes digestivas, dermatologicas, culinarias y cosméticas.",
        precio: 8,
        stock: 5,
    },
    {
        id: 3,
        nombre: "Calathea rosa",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//calathea%20-ornata.jpg",
        descripcion: "La calathea posee un follaje verde oscuro finamente estriado de rosa claro y al dorso de púrpura.",
        precio: 19.95,
        stock: 2,
    },
    {
        id: 4,
        nombre: "Crassula ovata hobbit",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//crassula%20ovata%20hobbit.jpg",
        descripcion: "Es una notable planta suculenta pequeña y muy decorativa de interior con un porte compacto.",
        precio: 7.55,
        stock: 5,
    },
    {
        id: 5,
        nombre: "Ficus benjamina",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//Ficus%20benjamina%20Danielle.jpg",
        descripcion: "El ficus de hoja pequeña es una planta purificante eficaz entre otros contra el amoniaco.",
        precio: 8.95,
        stock: 10,
    },
    {
        id: 6,
        nombre: "Frangipani blanco",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//Plumeria%20alba.jpg",
        descripcion: "Sus flores exhalan un poderoso perfume que recuerda al maravilloso olor de la frangipani.",
        precio: 59.50,
        stock: 7,
    },
    {
        id: 7,
        nombre: "Helecho de boston",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//Nephrolepis%20exaltata.jpg",
        descripcion: "El helecho de Boston es una planta purificadora muy eficaz contra el formadehido y el xileno.",
        precio: 4.50,
        stock: 8,
    },
    {
        id: 8,
        nombre: "Jazmin de madagascar",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//Stephanotis%20floribunda.jpg",
        descripcion: "Produce numerosas flores blancas muy perfumadas, desde la primavera hasta el otoño.",
        precio: 16.95,
        stock: 1,
    },
    {
        id: 9,
        nombre: "Palmera hawaiana",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//brighamia%20insignis.jpg",
        descripcion: "La palmera hawaiana, o brighamia, no es una verdadera palmera, sino una planta herbácea.",
        precio: 29.50,
        stock: 3,
    },
    {
        id: 10,
        nombre: "Pilea",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//pilea%20peperomioides.jpg",
        descripcion: "Sorprendente pequeña planta de interior muy decorativa gracias a sus hojas redondas, espesas y colgantes",
        precio: 13,
        stock: 9,
    },
    {
        id: 11,
        nombre: "Rosa del desierto",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//adenium%20obesum%20specimen.jpg",
        descripcion: "Tomar la precaución de lavarse las manos después de su poda debido a la toxicidad de su sabia.",
        precio: 35,
        stock: 1,
    },
    {
        id: 12,
        nombre: "Yuca pie de elefante",
        imagen: "https://www.planfor.es/Donnees_Site/Produit/Photo//Yucca%20elephantipes.jpg",
        descripcion: "Saca su nombre de la particularidad de que su tronco sea siempre mas ancho en la base.",
        precio: 64,
        stock: 6,
    },
];